// Code generated by "stringer -type=RequestSource"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Make-0]
	_ = x[ProjectBoard-1]
	_ = x[Stories-2]
	_ = x[YSC-3]
}

const _RequestSource_name = "MakeProjectBoardStoriesYSC"

var _RequestSource_index = [...]uint8{0, 4, 16, 23, 26}

func (i RequestSource) String() string {
	if i < 0 || i >= RequestSource(len(_RequestSource_index)-1) {
		return "RequestSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestSource_name[_RequestSource_index[i]:_RequestSource_index[i+1]]
}
